In [ ]:
%matplotlib inline

In [ ]:
from sklearn import svm
from sklearn.utils import shuffle
import matplotlib.pyplot as plt
import numpy as np
clf = svm.LinearSVC()

In [20]:
from scipy import io
training = scipy.io.loadmat("train.mat")

In [18]:
cd data/digit-dataset/

[Error 3] The system cannot find the path specified: u'data/digit-dataset/'
C:\Users\wpous\OneDrive\Documents\CS189\hw1\data\digit-dataset


In [87]:
import math

#benchmark.m, converted
def benchmark(pred_labels, true_labels):
    errors = pred_labels != true_labels
    err_rate = sum(errors) / float(len(true_labels))
    indices = errors.nonzero()
    return err_rate, indices

In [23]:
training

{'__globals__': [],
 '__header__': 'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Wed Jan 21 01:23:55 2015',
 '__version__': '1.0',
 'train_images': array([[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ..., 
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ..., 
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ..., 
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        ..., 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ..., 
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 

In [131]:
train_images = training['train_images']
train_images = train_images.reshape((28*28,-1)) #reshape so features are flattened to 1d
train_images = train_images.transpose() #transpose so sample number is first dimension

In [25]:
train_labels = training['train_labels']

In [26]:
len(train_labels)

60000

In [31]:
len(train_images[0][27])

60000

In [35]:
import numpy as np
a = np.array([[1,2],[3,4], [5,6]])

In [41]:
a = np.array([[1,2],[3,4], [5,6]])
a.reshape((2,3), order='C')

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
f =train_images[:][:][0]

In [64]:
trainedd = train_images[:,:,100]

In [60]:
train_images.shape

(28L, 28L, 60000L)

In [65]:
trainedd.shape

(28L, 28L)

In [67]:
import random


2

In [69]:
random.randint(1,3)

1

In [189]:
indices = set() #use set since we want unique indices and testing membership much faster than list
i = 0
total_indices = 50000
training_set_length = 60000 #60000- 10000 used as validation
while i < total_indices:
    index = random.randint(0,training_set_length-1)
    if index not in indices:
        indices.add(index)
        i += 1
validation_indices = set()
j = 0
validation_number = 10000 #do same thing to randomize validation number indices, so there is roughly even spread across training set (important if training set is ordered)
while j < validation_number:
    index = random.randint(0,training_set_length-1)
    if index not in indices:
        validation_indices.add(index)
        j += 1

In [191]:
validation_images = []
validation_labels = []
for n in validation_indices:
    validation_images.append(train_images[n,:])
    validation_labels.append(train_labels[n,0])
#validation_images = train_images[(60000-10000-1):(60000-1),:]
#validation_images = train_images[:,:,(60000-10000-1):(60000-1)] 
#validation_labels = train_labels[(60000-10000-1):(60000-1),0]

#validation_images = validation_images.reshape((28*28,-1)) #reshape so features are flattened to 1d
#validation_images = validation_images.transpose() #transpose so sample number is first dimension

In [192]:
selected_training = []
selected_training_labels = []
for n in indices:
    selected_training.append(train_images[n,:])
    #selected_training.append(np.ndarray.flatten(train_images[:,:,n])) #must flatten because scikit svm only takes 1d array of features
    selected_training_labels.append(train_labels[n,0])

In [193]:
clf.fit(selected_training,selected_training_labels)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [194]:
#clf.fit(validation_images, validation_labels)
predicted_labels = clf.predict(validation_images)

In [195]:
benchmark(predicted_labels, validation_labels)

(0.19243053337591823,
 (array([   1,    6,    7, ..., 6244, 6250, 6261], dtype=int64),))

In [98]:
test_shaping = np.reshape(validation_images, (28*28,-1))

In [104]:
test_shaping.shape

(10000L, 784L)

In [103]:
test_shaping =test_shaping.transpose()

In [157]:
len(b[0])

2060

In [166]:
a

0.3754735360969802

In [134]:
len(indices)

1000

In [141]:
indices

{10241,
 2,
 20485,
 36870,
 4501,
 24585,
 2058,
 4107,
 21783,
 22542,
 22505,
 26644,
 27993,
 43032,
 35844,
 10268,
 22557,
 16414,
 34847,
 38945,
 30754,
 16419,
 22564,
 28709,
 23324,
 38954,
 47148,
 43698,
 49199,
 30773,
 20534,
 17076,
 34874,
 45115,
 24636,
 40970,
 10302,
 43071,
 47168,
 21856,
 36875,
 34884,
 45125,
 20550,
 16458,
 24653,
 43087,
 43088,
 22609,
 30802,
 7865,
 39000,
 36954,
 23053,
 6238,
 32863,
 43104,
 18531,
 14436,
 34917,
 30822,
 45160,
 30825,
 16495,
 45168,
 2162,
 26739,
 12985,
 49280,
 22660,
 10373,
 41094,
 47239,
 9580,
 37003,
 43148,
 43151,
 16528,
 6290,
 45205,
 150,
 39065,
 2202,
 10397,
 30879,
 39696,
 30882,
 13167,
 169,
 10411,
 49324,
 34989,
 10415,
 14512,
 25288,
 37042,
 43765,
 26654,
 36553,
 43192,
 10426,
 35258,
 39104,
 35009,
 6338,
 12483,
 37061,
 43206,
 10440,
 39113,
 37066,
 28880,
 24786,
 47139,
 49364,
 30933,
 43222,
 10455,
 47323,
 20705,
 47331,
 2086,
 47334,
 48849,
 2282,
 25639,
 43244,
 309

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
c_matrix = confusion_matrix(validation_labels, predicted_labels)
print(c_matrix)
plt.figure()
plot_confusion_matrix(c_matrix)

In [1]:
def cross_validation(k_fold,):
    return 0

In [15]:
a, b = [1 ,2 ,3, 4, 5 ,6], [4, 5 ,6, 7,8,9]

In [16]:
c, d = shuffle(a,b)

In [17]:
c, d

([2, 4, 3, 6, 1, 5], [5, 7, 6, 9, 4, 8])

In [11]:
from sklearn.utils import shuffle